### ISSUE TITLE
ImportError: cannot import name '__version__' 

### ISSUE THREAD

**Issue by ancarnevali** [materialsproject/api#543]
Hi all!
I'm facing an error when importing MPRester from the `mp_api` module.
```
>>>from mp_api import MPRester
ImportError                               Traceback (most recent call last)
c:\Users\anton\Documents\PythonScripts\MP_API\MP_api_battery_data.py in <module>
      [7](file:///c%3A/Users/anton/Documents/PythonScripts/MP_API/MP_api_battery_data.py?line=6)[ import pymatgen.core as mg
      ]()[8](file:///c%3A/Users/anton/Documents/PythonScripts/MP_API/MP_api_battery_data.py?line=7)[ print("First imports ok")
----> ]()[9](file:///c%3A/Users/anton/Documents/PythonScripts/MP_API/MP_api_battery_data.py?line=8)[ from]()[ mp_api import MPRester
      ]()[10](file:///c%3A/Users/anton/Documents/PythonScripts/MP_API/MP_api_battery_data.py?line=9)[ mpr = MPRester()
     ]()[11](file:///c%3A/Users/anton/Documents/PythonScripts/MP_API/MP_api_battery_data.py?line=10)[ print("We got the rester")

~\miniconda3\envs\mp_api3\lib\site-packages\mp_api\__init__.py in <module>
      3 import os
      4 from pkg_resources import get_distribution, DistributionNotFound
----> 5 from mp_api.client import MPRester
      6 
      7 try:  # pragma: no cover

~\miniconda3\envs\mp_api3\lib\site-packages\mp_api\client.py in <module>
     11 from emmet.core.symmetry import CrystalSystem
     12 from emmet.core.vasp.calc_types import CalcType
---> 13 from emmet.core.summary import HasProps
     14 from mpcontribs.client import Client
     15 from pymatgen.analysis.magnetism import Ordering

~\AppData\Roaming\Python\Python39\site-packages\emmet\core\summary.py in <module>
      6 from pymatgen.core.structure import Structure
      7 
----> 8 from emmet.core.electronic_structure import BandstructureData, DosData
      9 from emmet.core.material_property import PropertyDoc
     10 from emmet.core.mpid import MPID

~\AppData\Roaming\Python\Python39\site-packages\emmet\core\electronic_structure.py in <module>
     24 
     25 from emmet.core.settings import EmmetSettings
---> 26 from emmet.core.material_property import PropertyDoc
     27 from emmet.core.mpid import MPID
     28 

~\AppData\Roaming\Python\Python39\site-packages\emmet\core\material_property.py in <module>
      8 from pymatgen.core import Structure
      9 
---> 10 from emmet.core.material import PropertyOrigin
     11 from emmet.core.mpid import MPID
     12 from emmet.core.structure import StructureMetadata

~\AppData\Roaming\Python\Python39\site-packages\emmet\core\material.py in <module>
      9 
     10 from emmet.core.mpid import MPID
---> 11 from emmet.core.structure import StructureMetadata
     12 from emmet.core.vasp.validation import DeprecationMessage
     13 

~\AppData\Roaming\Python\Python39\site-packages\emmet\core\structure.py in <module>
      9 from pymatgen.core.structure import Structure
     10 
---> 11 from emmet.core.base import EmmetBaseModel
     12 from emmet.core.symmetry import SymmetryData
     13 

~\AppData\Roaming\Python\Python39\site-packages\emmet\core\base.py in <module>
      6 from pymatgen.core import __version__ as pmg_version
      7 
----> 8 from emmet.core import __version__
      9 
     10 T = TypeVar("T", bound="EmmetBaseModel")

ImportError: cannot import name '__version__' from 'emmet.core' (C:\Users\anton\AppData\Roaming\Python\Python39\site-packages\emmet\core\__init__.py)]()
```
Importing MPRester from the canonic `pymatgen.ext.matproj` doesn't seem to have any problem.
The issue appears both if I install pymatgen with pip and conda, so I guess it should be linked to `mp_api` itself. I am running its `0.21.1` version on a Windows 10 machine.
Any help would be appreciated, thank you!

EDIT: 
- downgrading to `mp_api==0.20.6` yields the same error
- reinstalling `emmet.core` too

**Comment by munrojm** [comment]
Hi @ancarnevali, it looks like this is most likely an `emmet-core` version issue. Try updating and see if that fixes things. If not, let me know which version you have so I can take a closer look.

**Comment by ancarnevali** [comment]
No updates are available, I am working with `emmet-core` version `0.21.20`. I am working on a fresh environment where I conda-forged pymatgen and pip installed mp_api (see attached if needed).
[anc.txt](https://github.com/materialsproject/api/files/8176355/anc.txt)

**Comment by munrojm** [comment]
Unfortunately, I am having trouble recreating the issue. I have setup a new environment with your provided installation details. Running the import command in VSCode with that same ipykernel version yields no issues on my end. 

It looks like `emmet-core` is not in the output of your `conda list`? Have you tried using pip and `--force` to have it reinstall all `mp-api` dependencies in that environment?

**Comment by mkhorton** [comment]
I've seen the UserWarning for the MPContribs client before, someone posted about it on matsci.org, the client page has some troubleshooting here: https://pypi.org/project/mpcontribs-client/

Did you try to reproduce on Windows @munrojm ?

**Comment by munrojm** [comment]
Unfortunately, no. I tried on linux.

**Comment by munrojm** [comment]
Looks like the windows tests are failing due to the `mpcontribs` client not loading with the same warning: `Problem loading MPContribs client: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]`

**Comment by ancarnevali** [comment]
`pip install --upgrade --force-reinstall mp-api` gave me some problems, which I fixed by adding 'C:\Users\<username>\AppData\Roaming\Python\Python39\Scripts' to my environment variables. For some reason doing it manually wouldn't work, so I had to do it with a python script which I struggle to recover.

After that, the command worked ok. Here is the working env: [mp_working.txt](https://github.com/materialsproject/api/files/8196400/mp_working.txt)

Importing MPRester results now in the same warning @munrojm highlighted.

**Comment by munrojm** [comment]
Did you try setting the env variable referenced on https://pypi.org/project/mpcontribs-client/? 

```
Set the environment variable SSL_CERT_FILE to $(python -m certifi).
```

**Comment by ancarnevali** [comment]
I am not sure how to do it: I tried navigating to the Environment Variables and add manually a system variable SSL_CERT_FILE with value $(python -m certifi), but that did not get rid of the warning when importing MPRester. I get the warning only the first time I import in a Jupyter notebook.

**Comment by munrojm** [comment]
@ancarnevali, were you able to resolve this? Setting that environment variable to the output of that python command works for me in windows.

**Comment by ancarnevali** [comment]
Yes, it is fixed. I just receive the `twisted.python` warning you reported above after instantiating `MPRester()`, but everything seems to work. I'll close the issue!
